### ISSUE TITLE
can't push to master

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Epilepsy-Repository#3]
since @fepegar changing and reverting back changes in this repository (prior to SVT repository), I am unable to push to master without pulling - the most up to date for my puroses for the SVT project is the 'MegaAnalysis-March2020' branch (and otherwise the 'ML-paper' branch)

**Comment by fepegar** [comment]
Why unable? What did you do and what did you get?

**Comment by thenineteen** [comment]
This is now the error I receive when trying to push. I didn't get this error when pushing in the past not sure if it is to due with the cython files? It hasn't worked since you first changed then reverted the repo back. Note that we now have an [SVT repo](https://github.com/thenineteen/Semiology-Visualisation-Tool) and[ slicer repo](https://github.com/fepegar/EpilepsySemiology) so I don't really want to pull any changes from this origin master, I just want to push my changes:

![image](https://user-images.githubusercontent.com/10786099/77698194-1eca8880-6fa8-11ea-9c9e-c93a2f0930b1.png)

**Comment by fepegar** [comment]
You need to pull before pushing.

**Comment by thenineteen** [comment]
do i have to - because technically nothing ***should*** have been changed?

**Comment by thenineteen** [comment]
![image](https://user-images.githubusercontent.com/10786099/77835594-2a53b600-7146-11ea-83c3-f4b1da6aa82c.png)


I have a few commits to add as I didn't expect it to be behind master

**Comment by fepegar** [comment]
Yeah, it's weird. Can you submit to a different branch instead and open a PR, maybe that will show you what the "conflicts" are.

**Comment by thenineteen** [comment]
git pull --rebase seemed to have worked
